package View;

import Data.Venta;
import java.util.ArrayList;

public class PanelVentas extends javax.swing.JFrame {

    private ArrayList<Venta> ventas;
    public PanelVentas(ArrayList<Venta> venta) {
        this.ventas=venta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(ventas.size(), 0));

        for(int i=0;i<ventas.size();i++){
            this.add(new PanelVenta(ventas.get(i)));
        }
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
