package View;

import Data.*;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class PanelProducto extends javax.swing.JPanel {

    private Producto producto;
    private Cliente user;
    public PanelProducto(Producto producto, Cliente user){
        this.producto=producto;
        this.user=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addCarrito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        ImgProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgProductoActionPerformed(evt);
            }
        });
        add(ImgProducto);
        ImgProducto.setBounds(10, 40, 110, 110);
        /*ImageIcon icon=new ImageIcon(producto.getDirImage());
        Image img= icon.getImage();
        Image auximg=img.getScaledInstance(ImgProducto.getWidth(),ImgProducto.getHeight(),java.awt.Image.SCALE_SMOOTH);
        ImageIcon otroicon = new ImageIcon(auximg);*/
        ImageIcon icon=new ImageIcon(producto.getDirImage());
        Image img= icon.getImage();
        Image auximg=img.getScaledInstance(ImgProducto.getWidth(),ImgProducto.getHeight(),java.awt.Image.SCALE_SMOOTH);
        ImageIcon otroicon = new ImageIcon(auximg);
        ImgProducto.setIcon(otroicon);

        jLabel1.setText("Precio");
        jLabel1.setText("$"+String.valueOf(producto.getPrecio()));
        add(jLabel1);
        jLabel1.setBounds(20, 160, 110, 20);

        jLabel2.setText("Nombre");
        jLabel2.setText(producto.getNombre());
        add(jLabel2);
        jLabel2.setBounds(10, 4, 110, 30);

        addCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carrito.gif"))); // NOI18N
        addCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarritoActionPerformed(evt);
            }
        });
        add(addCarrito);
        addCarrito.setBounds(40, 250, 40, 30);

        jLabel3.setText("Codigo: ");
        jLabel3.setText("Codigo: "+producto.getCodigo());
        add(jLabel3);
        jLabel3.setBounds(20, 180, 100, 20);

        jLabel4.setText("Plataforma: ");
        jLabel4.setText("Plataforma: "+producto.getPlataforma());
        add(jLabel4);
        jLabel4.setBounds(20, 220, 100, 20);

        jLabel5.setText("Tipo: ");
        jLabel5.setText("Tipo: "+producto.getTipo());
        add(jLabel5);
        jLabel5.setBounds(20, 200, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void ImgProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImgProductoActionPerformed

    private void addCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarritoActionPerformed
        try {
            Carrito aux=  user.getCarrito();
            aux.addProducto(producto);
            user.setCarrito(aux);
            JOptionPane.showMessageDialog(null,"Operación exitosa");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_addCarritoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImgProducto;
    private javax.swing.JButton addCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
